import "./globals.css";
import type { Metadata } from "next";
import { Header } from "@/widgets/header/header";
import { Main } from "@/widgets/main";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <Header />
        <Main>{children}</Main>
      </body>
    </html>
  );
}
